### ISSUE TITLE
No Disable Hardware Button option

### ISSUE THREAD

**Issue by phi1m0ndBb** [NoisyFlake/BetterAlarm#1]
I hope this message finds you well. I am writing to provide feedback on the recent update to the BetterAlarm tweak.

It has come to my attention that the latest version of BetterAlarm no longer includes the "Disable Hardware Button" option, which previously allowed users to prevent the alarm from being dismissed using the hardware buttons on the device. This change has significantly impacted the functionality and effectiveness of the tweak in a negative way.

Previously, the "Disable Hardware Button" option was an essential feature that ensured alarms could not be easily dismissed, thereby improving reliability for users who rely on alarms for important reminders and wake-up calls. Without this feature, alarms can now be easily silenced by simply pressing the volume or power button, which greatly reduces the utility of BetterAlarm as a dependable alarm solution.

In light of this, I consider the removal of this feature to be a downgrade rather than an upgrade. The ability to disable the hardware buttons was a key aspect of what made BetterAlarm stand out from other alarm tweaks, and its absence compromises the tweak’s overall effectiveness.

I strongly urge you to reconsider this change and restore the "Disable Hardware Button" option in the next update. This feature is crucial for users who need a reliable and fail-safe alarm system. Addressing this issue promptly will help maintain the trust and satisfaction of your user base.

Thank you for your attention to this matter. I look forward to your timely response and hope for a swift resolution.

**Comment by NoisyFlake** [comment]
This reads like it was written by ChatGPT. 

Anyway, the feature wasn’t removed. There simply isn’t an option to enable/disable it anymore. Instead it’s enabled all the time, because I don’t see a reason why someone wouldn’t want to have this feature.

Best regards
